services:
  web:
    build:
      context: AlumniProject
      target: builder
    volumes:
      - ./AlumniProject:/AlumniProject
      - ./AlumniProject/db.sqlite3:/AlumniProject/db.sqlite3
    environment:
      - DEBUG=True
    expose:
      - "8000"  # only exposed inside the docker network
    restart: unless-stopped

  proxy:
    image: nginx:latest
    ports:
      - "8080:8080"  # HTTPS (secure)
      - "8000:8000"  # HTTP (for redirect)
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - web
